### ISSUE TITLE
How is this repository synchronized with ocaml/opam-repository ?

### ISSUE THREAD

**Issue by hhugo** [fdopen/opam-repository-mingw#108]
It would be nice to document the process by which this repository stays in sync (or not) with ocaml/opam-repository.
I never know how long I should wait until a release in ocaml/opam-repository propagates into this repo.

**Comment by fdopen** [comment]
Just add the regular repo as a second one (just with lower priority):
`opam repo add ...`
I have not been updating the repo regularly for some time now: https://fdopen.github.io/opam-repository-mingw/2021/02/26/repo-discontinued/

**Comment by phated** [comment]
@fdopen I recently tried that with setup-ocaml and it failed. I would love to get a working example added to @smorimoto's setup-ocaml so the ocaml community can have top-tier CI across Linux, Mac and Windows.

**Comment by smorimoto** [comment]
@phated See https://github.com/ocaml/setup-ocaml/pull/520.

**Comment by phated** [comment]
It seems that the setup-ocaml patch needed to be reverted. Do the 2 opam repositories collide?

**Comment by EricYoung37** [comment]
Does anyone know how to unistall OCam64 from Windows 10?

I know this may be asked in another thread, and actually someone did (https://github.com/fdopen/opam-repository-mingw/issues/109). However, there hasn't been any answer in that thread since June.

I can find the folder of OCaml64, and it takes up 2.82G on my disk. I'm not sure if deleting the folder is the best solution since there may be something to do with Cygwin64 which comes with the installation. There may also be something to do with Windows registry. I hope to get a clean removal. Thanks in advance for any advice!
