### ISSUE TITLE
Quitting Ocaml makes the shell hangs

### ISSUE THREAD

**Issue by anta40** [fdopen/opam-repository-mingw#33]
I'm on Windows 10 32-bit, running the latest ocaml (4.04.0)
After quitting the ocaml REPL (either by Ctrl-C or Ctrl-Z), the shell will hang
![orepl](https://cloud.githubusercontent.com/assets/16976/23242860/dde05d86-f9ad-11e6-8ff6-b2989781bf73.jpg)

If I'm not mistaken this doesn't occur in the previous version.

**Comment by fdopen** [comment]
Yes, I can reproduce it. But it also happens with older ocaml versions for me. It's probably a incompatibility between cygwin's tty emulation and the native ocaml toplevel that doesn't understand this emulation (I can't reproduce it with a native terminal like cmd.exe instead of mintty).

But there is a simple workaround: If you are using ocaml inside mintty or rxvt, just use `rlwrap ocaml` instead of `ocaml`.

**Comment by anta40** [comment]
Seems that `rlwrap ocaml` does the trick. I think the issue can be closed, yes? :)
