### ISSUE TITLE
Both installers fail unable to resolve hostname for cygwin

### ISSUE THREAD

**Issue by johnwhitington** [fdopen/opam-repository-mingw#86]
I tried to update today, by using the installer. But both 32 bit and 64 bit versions cannot complete, unable to download cygwin.

Is this known? Is there anything I can do to debug the problem?

**Comment by fdopen** [comment]
cygwin.com is known to be not very reliable. But usually it works again after a few minutes. Just try it again.

Or ping cygwin.com and call setup-x86_64.exe (https://cygwin.com/install.html) manually. If either command also fails, it is definitely not due to the installer. ( The installer just calls cygwin's  setup-x86_64.exe / setup-x86.exe with extra parameters to install additional packages. It doesn't change network specific settings. )

**Comment by johnwhitington** [comment]
Thanks. Still no luck today...

I am trying to install 4.11.0 over an installation of 4.08.0

I tried the manual installation, but the `opam init` step doesn't actually do anything -- no new compiler binary is downloaded. It just prompts to set up the .bash_profile, and that it is. Same thing with the source option.

Do I need to ask opam to remove the existing 4.08.0 compiler, or delete my whole cygwin installation and begin from scratch?

**Comment by fdopen** [comment]
The procedure is analogous to linux/osX, if you only want to switch to a newer OCaml version. You don't need to run the installer again:
```bash
opam switch create 4.11.1+mingw64c # create a new switch
opam switch remove your-previous-switch # delete any switch you don't need any longer
```

**Comment by johnwhitington** [comment]
Ah, of course. Thanks.
