### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by CookieHCl** [fdopen/opam-repository-mingw#89]
I've used a [graphical installer](https://fdopen.github.io/opam-repository-mingw/installation/), and I can't find uninstaller.  
Is deleting folder(C:\OCaml64) sufficient for clean uninstall?

**Comment by fdopen** [comment]
Yes, just remove the folder and all link to it. That should be enough. See https://cygwin.com/faq.html#faq.setup.uninstall-all for details. 

The installer does not further modify Windows settings, any changes are due to running the cygwin's setup, which unfortunately does not provide an uninstall feature.
